/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  generalPartition,
  PartitionAcceptEnum,
} from "../funcs/generalPartition.ts";
import { ClientSDK, RequestOptions } from "../lib/sdks.ts";
import * as operations from "./models/operations/index.ts";
import { unwrapAsync } from "./types/fp.ts";

export { PartitionAcceptEnum } from "../funcs/generalPartition.ts";

export class General extends ClientSDK {
  /**
   * Summary
   *
   * @remarks
   * Description
   */
  async partition(
    request: operations.PartitionRequest,
    options?: RequestOptions & { acceptHeaderOverride?: PartitionAcceptEnum },
  ): Promise<operations.PartitionResponse> {
    return unwrapAsync(generalPartition(
      this,
      request,
      options,
    ));
  }
}
