/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.ts";
import { General } from "./general.ts";

export class UnstructuredClient extends ClientSDK {
  private _general?: General;
  get general(): General {
    return (this._general ??= new General(this._options));
  }
}
